version: "3.3"

networks:
  mqtt:
    driver: bridge

services:
  mqtt:
    image: ${MOSQUITTO_IMAGE_EXT_AUTH}
    container_name: mqtt
    #privileged: true
    #cap_add:
    #  - ALL
    #  - SYS_PTRACE
    #security_opt:
    #  - seccomp:unconfined
    #  - apparmor:unconfined
    ports:
      - "1883:1883" #default mqtt port
      - "8883:8883"
    volumes:
      - ../../../docker/conf/mosquitto:/mosquitto/config:rw
      #- ./plugins:/mosquitto/plugins:rw
    networks:
      - mqtt
  mqtt-web:
    image: ${EMQX_WEB_CLIENT}
    container_name: mqtt-web
    ports:
      - "80:80"
    networks:
      - mqtt
